title: Alberta ELA Study Resources
description: Study guides for Alberta Grade 10-12 English Language Arts
url: "https://scudfei.github.io"
baseurl: "/StudyELA"

theme: null

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
